apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        firewall-injection: enabled
      annotations:
        xliic.com/protection-token: "apifirewall-protection-token"
        xliic.com/container-port: "8443"
        xliic.com/tls-secret-name: "ssl-secret"
        xliic.com/target-url: "http://localhost:80"
        xliic.com/server-name: foobar
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  type: NodePort
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: nginx
