apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixi
spec:
  selector:
    matchLabels:
      app: pixiapi-pixiapp
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pixiapi
        firewall-injection: enabled
      annotations:
        xliic.com/protection-token: "apifirewall-protection-token"
        xliic.com/http-only: "enabled"
        xliic.com/container-port: "8080"
        xliic.com/inject-secret-env-jwk: "jwt-keys/pixirsa.jwk"
        xliic.com/env-configmap: "apifirewall-props"
        xliic.com/logs-to-volume: "apifirewall-logs"
        xliic.com/target-url: http://localhost:8090
        xliic.com/server-name: pixiapi.42crunch.test

    spec:
      containers:
      - name: pixiapp
        image: 42crunch/pixi:v3
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pixisvc
spec:
  type: NodePort
  ports:
  - name: "api"
    port: 8090
    targetPort: 8080
  selector:
    app: pixiapp
